typography_spectrum: 0.01675866637378931
color:
  brandStrength: 0.16405695211142302
  lightness: 0.7763784846756607
  saturation: 0.9455133136361837
  rhythmicContrast: 0.7744716263841838
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
layout_spectrum: 0.3151939504314214
author:
  name: Roman Koudriavtsev
  email: romank21@solvestra.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a4fdc24e-01bd-4e35-bca9-4d8ca9de81e8.jpg
name: SOLVESTRA
favicon: null
title: data moderne
description: contemporary info tech consulting
